name: Deploy Node.js Application on UCD

on:
  workflow_dispatch:
    # push:
  #   branches:
  #     - main  # 或者你用于部署的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }} student@csi6220-1-vm2.ucd.ie << EOF
            cd ~/vue/COMP3030J/RuoYi-Cloud/ruoyi-ui
            git pull
            npm install
            nohup npm run dev > /dev/null 2>&1 &
            cd ../../comp3030j-front
            npm install
            nohup npm run dev > /dev/null 2>&1 &
          EOF
